include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable some strict rules for convenience
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_declarations: false
    avoid_print: false
    use_build_context_synchronously: false
    use_key_in_widget_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"
